language: haskell

env:
  - GHCVER=7.10.2 STACK_VERSION=0.1.10.0

sudo: false
cache:
  directories:
  - $HOME/.stack/

addons:
  postgresql: "9.3"

services:
  - postgresql

before_install:
  # stack
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - export STACK_FULLVERSION=stack-$STACK_VERSION-linux-x86_64
  - travis_retry curl -L https://github.com/commercialhaskell/stack/releases/download/v$STACK_VERSION/$STACK_FULLVERSION.tar.gz | tar xz --strip-components 1 -C ~/.local/bin $STACK_FULLVERSION/stack;
  - chmod a+x ~/.local/bin/stack

install:
  - stack --no-terminal setup
  - stack --no-terminal build --pedantic --only-snapshot
  - stack install hlint
  - stack install stack-hpc-coveralls-0.0.3.0

before_script:
  - psql -c "create role test with login password 'test';" -U postgres
  - psql -c 'create database peer_review_test owner=test;' -U postgres

script:
  - stack --no-terminal test --pedantic --coverage
  - hlint .

after_script:
  - shc peer-review-service peer-review-service-test
