#!/bin/sh

cd "$(dirname "$0")/.."

stack_url="https://github.com/commercialhaskell/stack"

stack setup
if [ $? -eq 0 ]; then
  echo "==> Stack: OK"
else
  echo "==> You need to install 'stack'"
  echo "==> Check out ${stack_url}"
  exit 1
fi

echo "==> Creating app.cfg configuration file"
cp app.cfg.example app.cfg

echo "==> Setup done!"

echo "==> You still need to setup postgres on localhost or use remote server"
echo "==> Setup it up by yourself or use projects own Docker file:"
echo "==> $ docker build -t peer-review-postgres database"
echo "==> $ script/run_db"
